version: "3.9"

services:
  app:
    build:
      context: .  # Assuming the Dockerfile is in the root of your project
    command: sh -c "python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/app  # Mapping the entire project directory to /app in the container
    ports:
      - "9000:9000"
    environment:
      DJANGO_DEBUG: "1"
      SECRET_KEY: "${SECRET_KEY}"
      DOMAIN: "${DOMAIN}"
      RDS_DB_NAME: "${DATABASE_NAME}"
      RDS_USERNAME: "${DATABASE_USER}"
      RDS_PASSWORD: "${DATABASE_PASSWORD}"
      RDS_HOSTNAME: "${DATABASE_HOST}"
      RDS_PORT: "${DATABASE_PORT}"
      DJANGO_ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS}"  # Add this if required
